### ISSUE TITLE
Partitioned Table may fail w/o Default Partition

### ISSUE THREAD

**Issue by ghost** [faisaltheparttimecoder/mock-data#1]
Easiest solution here would be to ALTER any table without a default -- but potentially should scan for available ranges.

**Comment by faisaltheparttimecoder** [comment]
Thanks @brendanstephens for raising the issue, yes you are right mockD has an issue with partition tables mainly because it seems harder to fix all the check constraints on the table (compared to PK, FK , UK) and partitions are built with check constraints on top of it, so until a proper solution to understand and translate the check constraint into the working solution we will have to ignore partition table for now, this has been highlighted on the known issue section.

----------
## Known Issues
+ When using a small amount of rows and having defined a composite PK index, there are chances that the primary key would fail (this is due to foreign key fix only runs after primary key fix)
+ Still having issues with Check constraint, only check that works is "COLUMN > 0"
+ On Greenplum Database/HAWQ partition tables are not supported (due to check constraint issues defined above)
+ Custom datatypes are not supported
----------

**Comment by faisaltheparttimecoder** [comment]
This is now somewhat fixed on the v2.0 of the mock tool. The tool still has trouble with check constraints, so anything related to check and custom datatypes users have to use the custom sub command to load random data.

For more information on the custom subcommand check out [here](https://github.com/pivotal-legacy/mock-data/wiki/Sub-command:-Custom), it has steps on how to load to a partition table for example.

closing it as fixed
