### ISSUE TITLE
Encountered error when connecting to the database, err: FATAL #28000 SSL connection is required. Please specify SSL options and retry

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [faisaltheparttimecoder/mock-data#36]
How to specify SSL mode here? i'm trying with env variable PGSSLMODE but it seems it is not working

**Comment by faisaltheparttimecoder** [comment]
Hello @AwdotiaRomanowna , its currently not implemented inside the tool, i guess its `disabled` by default by the pkg `github.com/go-pg/pg`

https://github.com/pivotal-gss/mock-data/blob/master/helpers.go#L23

I'm not sure if the package `"github.com/go-pg/pg"` overrides or forces the `sslmode=disable` thus having no effect on the environment variable which you placed, need to check. 

Will use this issue has an enhancement, since I was under the impression most test database don't have any SSLmode  enabled :D

**Comment by AwdotiaRomanowna** [comment]
if you have your test db hosted on Azure it is enabled :)

**Comment by faisaltheparttimecoder** [comment]
Understood. I will take a look and play around with `"github.com/go-pg/pg"`, thanks for letting me know

**Comment by faisaltheparttimecoder** [comment]
Hello @AwdotiaRomanowna .

Apologise for the long wait, I had a look at the library `go-pg` which I have used to make a database connection and it seems like they dont have `sslmode` options has an argument

https://github.com/go-pg/pg/blob/v10/options.go#L24-L97

However, they do support the `sslmode` if supplied via connection URI.

https://github.com/go-pg/pg/blob/v10/options.go#L24-L97

`mock-data` v2.7 now support database connection via the URI, this is now documented here

https://github.com/pivotal-gss/mock-data/wiki/Connecting-to-Database

You can toggle the sslmode using the connection URI, if ssl is enabled on postgres db.

closing as implemented
